spring:
  data:
    cassandra:
#      keyspace-name: usersSpace
#      keyspace-name: muruKeyspace
#      keyspace.table
      port: 9042
      contact-points: localhost
datasource: usersSpace.users
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
  ignored: /resources/public/*
github:
  client:
    clientId: 2faca6c6adfb6e7e7180
    clientSecret: f511bfb58c44df55c8c68a8e05e9ccbde46622a4
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    authenticationScheme: query
    scope: user
  resource:
    userInfoUri: https://api.github.com/user
    token-type: bearer

vk:
  client:
    client-id: 5930440
    clientSecret: 4BR4NaEpP61pwCM862Y5
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
    tokenName: code
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email,
    pre-established-redirect-uri: http://localhost:8080/create
  resource:
    userInfoUri: https://api.vk.com/method/users.get
logging:
  level:
    org.springframework.security: DEBUG